[template]
src = "ost-config.php.tmpl"
dest = "/app/include/ost-config.php"
keys = [
    "/database/host",
    "/database/name",
    "/database/user",
    "/database/pass",
    "/database/port",
    "/database/prefix",
    "/admin/email",
    "/secret/salt",
]
